### ISSUE TITLE
Licensing stuff problems

### ISSUE THREAD

**Issue by TTtie** [TheBobPony/bobpony.org#10]
Steps to reproduce issue: 
- None

Explanation:
The Copying the website in README.md section says that you are not allowed to copy the website.
However, the LICENSE file states that it is licensed under the MIT license.
Which one does apply?

**Comment by TheBobPony** [comment]
"Please do not copy this website without permission from me, thanks."

Basically, ask me for permission if you want to use the contents, but don't copy the whole thingy.

Probably not sure what license it could fall under 🤔 but might keep MIT or replace it with smth that applies.

**Comment by TTtie** [comment]
inb4 all rights reserved.

**Comment by TTtie** [comment]
The LICENSE file is literally some legalese that grants some permissions.

It can even contain simple text like

```
Copyright (C) 2018 Bob Pony

All rights reserved.```
