### ISSUE TITLE
404.html for 404 page not working

### ISSUE THREAD

**Issue by TheBobPony** [TheBobPony/bobpony.org#12]
Steps to reproduce issue: 
1. Go to any non-existent page.
2. An 404 error page that doesn't use the 404.html

Explanation:

404.html isn't being picked up for whatever reason, someone please solve it. Thanks.

**Comment by TTtie** [comment]
This may explain 
![obrazek](https://user-images.githubusercontent.com/17570452/43358738-aae491ee-9296-11e8-945a-8c01eff43b14.png)

**Comment by TheBobPony** [comment]
Well I have 404.html in the root but for reason it does that.

**Comment by TTtie** [comment]
Found a fix, pushing out now.
